import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LingoWrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="flex justify-center bg-blue-200 py-5">
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold">LingoWrite</h1>
          </div>      
          <div className="bg-blue-600">
            <nav className="flex flex-wrap gap-4 sm:gap-6 justify-center py-3 sm:py-4 text-white font-semibold text-sm sm:text-base ">
              <Link href="/" className="hover:text-foreground">Home</Link>
              <Link href="#features" className="hover:text-foreground">Features</Link>
              <Link href="#exercises" className="hover:text-foreground">Exercises</Link>
              <Link href="#test" className="hover:text-foreground">Level Test</Link>
              <Link href="#about" className="hover:text-foreground scroll-smooth">About</Link>
            </nav>
          </div>
        </header>
        {children}
      <footer>
        <div className="bg-foreground text-background py-10 text-lg sm:text-xl text-center">
          <p>&copy; 2025 LingoWrite. All rights reserved.</p>
        </div>
      </footer>
      </body>
    </html>
  );
}
